CREATE TABLE IF NOT EXISTS HISTORY (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	EXECUTED_AT DATETIME NOT NULL,
	CMDS TEXT NOT NULL,
	PANE_COUNT INTEGER NOT NULL,
	WTCMD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FAVOURITE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CMDS TEXT NOT NULL,
	WTCMD TEXT NOT NULL
);