# Controls whether the terminal maximizes when opened
# Note: This feature only works when `open_in_new_tab` is set to false
# If `open_in_new_tab` is true, this setting is ignored
# and the terminal will follow the current terminal size
maximize: true

# Determines the orientation of the terminal pane arrangement (horizontal or vertical).
direction: horizontal

# Defines the number of fixed columns in the terminal layout; rows are auto-calculated.
columns: 2

# Specifies if the terminal should open in a new tab or a new window. If set to false, the app will open in new windows and the maximize effect will take place if set to true.
open_in_new_tab: true